### ISSUE TITLE
PDOStatement::fetchObject() signature

### ISSUE THREAD

**Issue by umulmrum** [JetBrains/phpstorm-stubs#29]
I subclassed the PDOStatement class, overwriting the fetchObject() method. When using the signature taken from the PHPStorm stubs, the PHP interpreter complains when strict mode is enabled:

> Strict standards: Declaration of ProfilerStatement::fetchObject() should be compatible with  PDOStatement::fetchObject($class_name = NULL, $ctor_args = NULL)

The stub's signature looks like this:

> public function fetchObject ($class_name = "stdClass", array $ctor_args = null)

There is no warning if I use this signature:

> public function fetchObject($class_name = null, $ctor_args = null)

The PHP source says the same if I interpret it correctly (I might as well be wrong): https://github.com/php/php-src/blob/master/ext/pdo/pdo_stmt.c#L1296
Is this an error in the stub?

Thank you!

edit: The PHP documentation uses the same signature as the stub: http://php.net/manual/en/class.pdostatement.php

**Comment by sekjun9878** [comment]
You should open this issue on https://youtrack.jetbrains.com/issues/WI?

**Comment by neuro159** [comment]
obsolete
