### ISSUE TITLE
Add 'CONTRIBUTING.md' and describe coding-standards used

### ISSUE THREAD

**Issue by thaJeztah** [JetBrains/phpstorm-stubs#3]
Adding a `CONTRIBUTING.md` file to the repository should automatically notify GitHub users that there are specific guidelines for contributing (as explained in [this GitHub blog](https://github.com/blog/1184-contributing-guidelines))

From the source code, it isn't directly clear what coding-standards are used, for example, in this block, the indenting is "off" (possibly due to mixed tabs/spaces); [mongo.php#L492-L502](https://github.com/JetBrains/phpstorm-stubs/blob/e97b771aa75e482579d6c20f12bc64a334a97600/mongo.php#L492-L502)

HTML looks to be used in the doc-blocks, but not consistently (sometimes [a `<br />`](https://github.com/JetBrains/phpstorm-stubs/blob/e97b771aa75e482579d6c20f12bc64a334a97600/mongo.php#L512), sometimes [just a NewLine](https://github.com/JetBrains/phpstorm-stubs/blob/e97b771aa75e482579d6c20f12bc64a334a97600/mongo.php#L572)). The PhpDoc documentation specifies that [MarkDown should be used for markup](http://www.phpdoc.org/docs/latest/guides/docblocks.html#description) in PhpDoc (although HTML is of course allowed in MarkDown);

> The nice thing about this description is that you can format your text according to Markdown, more specifically `Github-flavoured Markdown`_. Using this format it is easy to make your text bold, add inline code examples or easily generate links to other sites.

**Comment by neuro159** [comment]
Thank you!
