### ISSUE TITLE
Description of valid file pointer is wrong in filesystem functions

### ISSUE THREAD

**Issue by SDKiller** [JetBrains/phpstorm-stubs#38]
https://github.com/JetBrains/phpstorm-stubs/blob/master/standard_5.php

![22222222222](https://cloud.githubusercontent.com/assets/2150916/9149797/be011d4a-3dc3-11e5-878a-51b916d427dd.png)

See

https://github.com/JetBrains/phpstorm-stubs/blob/master/standard_5.php#L473

According to http://php.net/manual/en/function.fgets.php

> The file pointer must be valid, and must point to a file successfully opened by fopen() or fsockopen() (and not yet closed by fclose()).

As I could guess `&fs.validfp.all` is a reference to description but it is not substituted.

Compare with

https://github.com/JetBrains/phpstorm-stubs/blob/master/standard_5.php#L450

where description is set directly.

**Comment by SDKiller** [comment]
https://youtrack.jetbrains.com/issue/WI-28365

**Comment by neuro159** [comment]
fixed
