### ISSUE TITLE
Multiple definitions for SplType related classes

### ISSUE THREAD

**Issue by kicken** [JetBrains/phpstorm-stubs#39]
PR #4 added a new file for the classes in the SplType extension, but these were already defined in SPL_c1.php.  PHPStorm 9.0 is showing multiple definition warnings due to this.

![SplEnum multiple definitions](http://i.imgur.com/gS4EChM.png)

**Comment by MaXal** [comment]
Please create an issue at: https://youtrack.jetbrains.com/issues/WI

**Comment by neuro159** [comment]
fixed
